
module DashHtmlComponents
using Dash

const resources_path = realpath(joinpath( @__DIR__, "..", "deps"))
const version = "1.0.1"

include("html_a.jl")
include("html_abbr.jl")
include("html_acronym.jl")
include("html_address.jl")
include("html_area.jl")
include("html_article.jl")
include("html_aside.jl")
include("html_audio.jl")
include("html_b.jl")
include("html_base.jl")
include("html_basefont.jl")
include("html_bdi.jl")
include("html_bdo.jl")
include("html_big.jl")
include("html_blink.jl")
include("html_blockquote.jl")
include("html_br.jl")
include("html_button.jl")
include("html_canvas.jl")
include("html_caption.jl")
include("html_center.jl")
include("html_cite.jl")
include("html_code.jl")
include("html_col.jl")
include("html_colgroup.jl")
include("html_command.jl")
include("html_content.jl")
include("html_data.jl")
include("html_datalist.jl")
include("html_dd.jl")
include("html_del.jl")
include("html_details.jl")
include("html_dfn.jl")
include("html_dialog.jl")
include("html_div.jl")
include("html_dl.jl")
include("html_dt.jl")
include("html_element.jl")
include("html_em.jl")
include("html_embed.jl")
include("html_fieldset.jl")
include("html_figcaption.jl")
include("html_figure.jl")
include("html_font.jl")
include("html_footer.jl")
include("html_form.jl")
include("html_frame.jl")
include("html_frameset.jl")
include("html_h1.jl")
include("html_h2.jl")
include("html_h3.jl")
include("html_h4.jl")
include("html_h5.jl")
include("html_h6.jl")
include("html_header.jl")
include("html_hgroup.jl")
include("html_hr.jl")
include("html_i.jl")
include("html_iframe.jl")
include("html_img.jl")
include("html_ins.jl")
include("html_isindex.jl")
include("html_kbd.jl")
include("html_keygen.jl")
include("html_label.jl")
include("html_legend.jl")
include("html_li.jl")
include("html_link.jl")
include("html_listing.jl")
include("html_main.jl")
include("html_mapel.jl")
include("html_mark.jl")
include("html_marquee.jl")
include("html_meta.jl")
include("html_meter.jl")
include("html_multicol.jl")
include("html_nav.jl")
include("html_nextid.jl")
include("html_nobr.jl")
include("html_noscript.jl")
include("html_objectel.jl")
include("html_ol.jl")
include("html_optgroup.jl")
include("html_option.jl")
include("html_output.jl")
include("html_p.jl")
include("html_param.jl")
include("html_picture.jl")
include("html_plaintext.jl")
include("html_pre.jl")
include("html_progress.jl")
include("html_q.jl")
include("html_rb.jl")
include("html_rp.jl")
include("html_rt.jl")
include("html_rtc.jl")
include("html_ruby.jl")
include("html_s.jl")
include("html_samp.jl")
include("html_script.jl")
include("html_section.jl")
include("html_select.jl")
include("html_shadow.jl")
include("html_slot.jl")
include("html_small.jl")
include("html_source.jl")
include("html_spacer.jl")
include("html_span.jl")
include("html_strike.jl")
include("html_strong.jl")
include("html_sub.jl")
include("html_summary.jl")
include("html_sup.jl")
include("html_table.jl")
include("html_tbody.jl")
include("html_td.jl")
include("html_template.jl")
include("html_textarea.jl")
include("html_tfoot.jl")
include("html_th.jl")
include("html_thead.jl")
include("html_time.jl")
include("html_title.jl")
include("html_tr.jl")
include("html_track.jl")
include("html_u.jl")
include("html_ul.jl")
include("html_var.jl")
include("html_video.jl")
include("html_wbr.jl")
include("html_xmp.jl")

function __init__()
    Dash.register_package(
        Dash.ResourcePkg(
            "dash_html_components",
            resources_path,
            version = version,
            [
                Dash.Resource(
    relative_package_path = "dash_html_components.min.js",
    external_url = "https://unpkg.com/dash-html-components@1.0.1/dash_html_components/dash_html_components.min.js",
    dynamic = nothing,
    async = nothing,
    type = :js
),
Dash.Resource(
    relative_package_path = "dash_html_components.min.js.map",
    external_url = "https://unpkg.com/dash-html-components@1.0.1/dash_html_components/dash_html_components.min.js.map",
    dynamic = true,
    async = nothing,
    type = :js
)
            ]
        )
    )
end
end
